In [7]:
import pandas as pd

df = pd.read_csv("customer_churn.csv")

print("Head:\n", df.head())
print("Tail:\n", df.tail())
df.info()
print("Description:\n", df.describe())

Head:
    customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No     1.0           No
1  5575-GNVDE    Male              0      No         No    34.0          Yes
2  3668-QPYBK    Male              0      No         No     2.0          Yes
3  7795-CFOCW    Male              0      No         No    45.0           No
4  9237-HQITU  Female              0      No         No     2.0          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   NaN
3  Bank transfer (automatic)          42.30       1840.75   NaN
4           Electronic check          70.70        151.65   NaN

[5 rows x 21 columns]
Tail:
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes    24.0
7039  2234-XADUH  Female              0     Yes        Yes    72.0
7040  4801-JZAZL  Female              0     Yes        Yes    11.0
7041  8361-LTMKD    Male              1     Yes         No     4.0
7042  3186-AJIEK    Male              0      No         No    66.0

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
7038    No
7039    No
7040    No
7041   Yes
7042    No

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7035 non-null   float64
 6   PhoneService      7035 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7035 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7035 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7037 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB
Description:
        SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7035.000000     7043.000000
mean        0.162147    32.365601       64.761692
std         0.368612    24.558500       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [8]:
df_sorted = df.sort_values(by="customerID", ascending=False)
print("Head (descending order):\n", df_sorted.head())

Head (descending order):
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
1634  9995-HOTOH    Male              0     Yes        Yes    63.0
1996  9993-LHIEB    Male              0     Yes        Yes    67.0
1260  9992-UJOEL    Male              0      No         No     2.0
2875  9992-RRAMN    Male              0     Yes         No    22.0
3607  9987-LUTYD  Female              0      No         No    13.0

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
1634           No  No phone service             DSL            Yes  ...
1996          Yes                No             DSL            Yes  ...
1260          Yes                No             DSL             No  ...
2875          Yes               Yes     Fiber optic             No  ...
3607          Yes                No             DSL            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1634              Yes          No         Yes             Yes        Two year
1996              Yes         Yes          No             Yes        Two year
1260               No          No          No              No  Month-to-month
2875               No          No          No             Yes  Month-to-month
3607               No         Yes          No              No        One year

     PaperlessBilling     PaymentMethod MonthlyCharges  TotalCharges Churn
1634               No  Electronic check          59.00        3707.6    No
1996               No      Mailed check          67.85       4627.65    No
1260              Yes      Mailed check          50.30         92.75    No
2875              Yes  Electronic check          85.10        1873.7   Yes
3607               No      Mailed check          55.15         742.9    No

[5 rows x 21 columns]

In [9]:
df_sorted = df.sort_values(by="customerID", ascending=True)
print("Head (ascending order):\n", df_sorted.head())

Head (ascending order):
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
2307  0002-ORFBO  Female              0     Yes        Yes     9.0
3488  0003-MKNFE    Male              0      No         No     9.0
3845  0004-TLHLJ    Male              0      No         No     4.0
5931  0011-IGKFF    Male              1     Yes         No    13.0
5569  0013-EXCHZ  Female              1     Yes         No     3.0

     PhoneService MultipleLines InternetService OnlineSecurity  ...  \
2307          Yes            No             DSL             No  ...
3488          Yes           Yes             DSL             No  ...
3845          Yes            No     Fiber optic             No  ...
5931          Yes            No     Fiber optic             No  ...
5569          Yes            No     Fiber optic             No  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
2307               No         Yes         Yes              No        One year
3488               No          No          No             Yes  Month-to-month
3845              Yes          No          No              No  Month-to-month
5931              Yes          No         Yes             Yes  Month-to-month
5569               No         Yes         Yes              No  Month-to-month

     PaperlessBilling     PaymentMethod MonthlyCharges  TotalCharges Churn
2307              Yes      Mailed check           65.6         593.3    No
3488               No      Mailed check           59.9         542.4    No
3845              Yes  Electronic check           73.9        280.85   Yes
5931              Yes  Electronic check           98.0       1237.85   Yes
5569              Yes      Mailed check           83.9         267.4   Yes

[5 rows x 21 columns]

In [10]:
df['SeniorCitizen'] = df['SeniorCitizen'].map({1: 'Yes', 0: 'No'})
print(df[['SeniorCitizen']].head())

  SeniorCitizen
0            No
1            No
2            No
3            No
4            No

In [11]:
df['MonthlyChargePerYear'] = df['MonthlyCharges'] * df['tenure']

print(df[['MonthlyCharges', 'MonthlyChargePerYear']].head())

   MonthlyCharges  MonthlyChargePerYear
0           29.85                 29.85
1           56.95               1936.30
2           53.85                107.70
3           42.30               1903.50
4           70.70                141.40

In [12]:
df['MonthlyChargePerYear'] = df['MonthlyCharges'] * 12

print(df[['MonthlyCharges', 'MonthlyChargePerYear']].head())

   MonthlyCharges  MonthlyChargePerYear
0           29.85                 358.2
1           56.95                 683.4
2           53.85                 646.2
3           42.30                 507.6
4           70.70                 848.4

In [13]:
# Subset

df_subset = df[df["tenure"] > 24]
print(df_subset.head())

    customerID  gender SeniorCitizen Partner Dependents  tenure PhoneService  \
1   5575-GNVDE    Male            No      No         No    34.0          Yes
3   7795-CFOCW    Male            No      No         No    45.0           No
8   7892-POOKP  Female            No     Yes         No    28.0          Yes
9   6388-TABGU    Male            No      No        Yes    62.0          Yes
12  8091-TTVAX    Male            No     Yes         No    58.0          Yes

       MultipleLines InternetService OnlineSecurity  ... TechSupport  \
1                 No             DSL            Yes  ...          No
3   No phone service             DSL            Yes  ...         Yes
8                Yes     Fiber optic             No  ...         NaN
9                 No             DSL            Yes  ...         NaN
12               Yes     Fiber optic             No  ...         NaN

   StreamingTV StreamingMovies        Contract PaperlessBilling  \
1           No              No        One year               No
3           No              No        One year               No
8          Yes             Yes  Month-to-month              Yes
9           No              No        One year               No
12         Yes             Yes             NaN               No

                PaymentMethod MonthlyCharges TotalCharges  Churn  \
1                Mailed check          56.95       1889.5     No
3   Bank transfer (automatic)          42.30      1840.75    NaN
8            Electronic check         104.80      3046.05    Yes
9   Bank transfer (automatic)          56.15      3487.95     No
12    Credit card (automatic)         100.35       5681.1     No

   MonthlyChargePerYear
1                 683.4
3                 507.6
8                1257.6
9                 673.8
12               1204.2

[5 rows x 22 columns]

In [14]:
df_churned = df[df["Churn"] == 'Yes']
print(df_churned.head())

    customerID  gender SeniorCitizen Partner Dependents  tenure PhoneService  \
8   7892-POOKP  Female            No     Yes         No    28.0          Yes
13  0280-XJGEX    Male            No      No         No     NaN          NaN
18  4190-MFLUW  Female            No     Yes        Yes     NaN          NaN
20  8779-QRDMV    Male           Yes      No         No     NaN          NaN
22  1066-JKSGK    Male            No      No         No     1.0          Yes

       MultipleLines InternetService       OnlineSecurity  ...  \
8                Yes     Fiber optic                   No  ...
13               Yes     Fiber optic                   No  ...
18                No             DSL                   No  ...
20  No phone service             DSL                   No  ...
22                No              No  No internet service  ...

            TechSupport          StreamingTV      StreamingMovies  \
8                   NaN                  Yes                  Yes
13                   No                  Yes                  Yes
18                  Yes                   No                   No
20                   No                   No                  Yes
22  No internet service  No internet service  No internet service

          Contract PaperlessBilling              PaymentMethod MonthlyCharges  \
8   Month-to-month              Yes           Electronic check         104.80
13             NaN              Yes  Bank transfer (automatic)         103.70
18             NaN               No    Credit card (automatic)          55.20
20  Month-to-month              Yes           Electronic check          39.65
22  Month-to-month               No               Mailed check          20.15

   TotalCharges  Churn MonthlyChargePerYear
8       3046.05    Yes               1257.6
13       5036.3    Yes               1244.4
18       528.35    Yes                662.4
20        39.65    Yes                475.8
22        20.15    Yes                241.8

[5 rows x 22 columns]

In [15]:
# Aggregate

df_agg = df.groupby('Contract').agg({'MonthlyCharges': 'mean'})
print(df_agg)
print()
df_agg_internet_service = df[df['Churn'] == 'Yes'].groupby('InternetService').size()
print(df_agg_internet_service)

                MonthlyCharges
Contract
Month-to-month       66.375536
One year             65.054793
Two year             60.712286

InternetService
DSL             458
Fiber optic    1295
No              113
dtype: int64

In [16]:
df.at[4, 'MonthlyCharges'] += 5
print(df.loc[4, 'MonthlyCharges'])

75.7

In [17]:
df.at[5, 'MonthlyCharges'] -= 9.65
print(df.loc[5, 'MonthlyCharges'])

90.0

In [18]:
df.at[0, 'MonthlyCharges'] *= 3
print(df.loc[0, 'MonthlyCharges'])

89.55000000000001

In [19]:
df.at[36, 'MonthlyCharges'] /= 3
print(df.loc[36, 'MonthlyCharges'])

23.233333333333334

In [20]:
tenure_greater = df.at[0, 'tenure'] > df.at[9, 'tenure']
print(tenure_greater)

False

In [21]:
tenure_equal = df.at[2, 'tenure']  == df.at[4, 'tenure']
print(tenure_equal)

True

In [22]:
both_services_count = df[(df['TechSupport'] == 'Yes') & (df['StreamingTV'] == 'Yes')].shape[0]
print(both_services_count)

1217

In [23]:
internet_dsl_fiber = df[(df['InternetService'] == 'DSL') | (df['InternetService'] == 'Fiber optic')].shape[0]
print(internet_dsl_fiber)

5517

In [24]:
senior_male_electronic = df[(df['SeniorCitizen'] == 'Yes') & (df['gender'] == 'Male') & (df['PaymentMethod'] == 'Electronic check')].shape[0]
print(senior_male_electronic)

298

In [25]:
missing_values_count = df.isnull().sum().sum()
print(missing_values_count)

38

In [26]:
df = pd.read_csv("customer_churn_original.csv")

dsl_tenure_above_45 = df[(df['InternetService'] == 'DSL') & (df['tenure'] > 45)]
print(dsl_tenure_above_45.head())

    customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
9   6388-TABGU    Male              0      No        Yes      62          Yes
23  3638-WEABW  Female              0     Yes         No      58          Yes
24  6322-HRPFA    Male              0     Yes        Yes      49          Yes
28  5248-YGIJN    Male              0     Yes         No      72          Yes
41  9489-DEDVP  Female              0     Yes        Yes      70          Yes

   MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
9             No             DSL            Yes  ...               No
23           Yes             DSL             No  ...               No
24            No             DSL            Yes  ...               No
28           Yes             DSL            Yes  ...              Yes
41           Yes             DSL            Yes  ...               No

   TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
9           No          No              No        One year               No
23         Yes          No              No        Two year              Yes
24         Yes          No              No  Month-to-month               No
28         Yes         Yes             Yes        Two year              Yes
41          No         Yes              No        Two year              Yes

                PaymentMethod MonthlyCharges  TotalCharges Churn
9   Bank transfer (automatic)          56.15       3487.95    No
23    Credit card (automatic)          59.90        3505.1    No
24    Credit card (automatic)          59.60        2970.3    No
28    Credit card (automatic)          90.25       6369.45    No
41    Credit card (automatic)          69.20       4872.35    No

[5 rows x 21 columns]

In [27]:
max_tenure = df['MonthlyCharges'].max()
print(max_tenure)

118.75

In [32]:
def category(tenure):
    if(tenure <= 25 and tenure > 1):
        return 'Low'
    elif(tenure <= 50 and tenure > 25):
        return 'Medium'
    elif(tenure<=100 and tenure > 50):
        return 'High'
    else:
        return 'Invalid'

df['Tenure_Grade'] = [category(tenure) for tenure in df['tenure']]
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Tenure_Grade
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Invalid
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,Medium
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Low
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Medium
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Low

In [35]:
df.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Tenure_Grade
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False